// Alert Registry — Operational Alerts for Arruda AI Ops
// READ-ONLY definitions — no actual notifications sent

import type { Alert, GovernanceItem } from './types';

export const alerts: Alert[] = [
  {
    id: 'alert-001',
    title: 'Claw3D builder executando sem feature ativa',
    description: 'LC-01 executa todo minuto via cron, mas feature está desabilitada. Gasta recursos sem propósito.',
    severity: 'warning',
    category: 'automation',
    source: 'cron-audit',
    serviceId: 'lc-01',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['none'],
    triggerCondition: 'cron LC-01 executado + feature flag = false',
    isActive: false,
    resolvedAt: new Date().toISOString(),
    acknowledgedBy: 'system',
    quarantineNote: 'Pausado via crontab 2026-05-06 — feature desabilitada, 277 falhas consecutivas',
  },
  {
    id: 'alert-002',
    title: 'Builderfy cron com syntax error',
    description: 'LC-07 executa comando com sintaxe quebrada a cada 1min. Comando é ignorado silenciosamente.',
    severity: 'error',
    category: 'automation',
    source: 'cron-audit',
    serviceId: 'lc-07',
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['none'],
    triggerCondition: 'cron LC-07 exit_code != 0',
    isActive: true,
  },
  {
    id: 'alert-003',
    title: 'remote-access-research com loop de timeout',
    description: 'OC-01 faz fetch a cada 5min mas dá timeout sempre. Retry 3x sem sucesso. Gera logs de erro toda hora.',
    severity: 'error',
    category: 'automation',
    source: 'cron-audit',
    serviceId: 'oc-01',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['none'],
    triggerCondition: 'OC-01 cron timeout + 3 retries',
    isActive: false,
    resolvedAt: new Date().toISOString(),
    acknowledgedBy: 'system',
    quarantineNote: 'OpenClaw cron job 6366c61d disabled 2026-05-06 — node desconectado, timeout loop',
  },
  {
    id: 'alert-004',
    title: '5 automações órfãs sem owner',
    description: 'Automations OC-02, OC-03, OC-04, OC-05, OC-06 não têm owner definido há mais de 7 dias.',
    severity: 'warning',
    category: 'automation',
    source: 'automation-registry',
    serviceId: 'registry',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['none'],
    triggerCondition: 'automation.owner = undefined/null há mais de 7 dias',
    isActive: true,
  },
  {
    id: 'alert-005',
    title: '3 automações em estado DANGEROUS',
    description: 'LC-01, LC-07, OC-01 estão marcadas como DANGEROUS no registry. Execução pode causar instabilidade.',
    severity: 'critical',
    category: 'automation',
    source: 'automation-registry',
    serviceId: 'registry',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['telegram'],
    triggerCondition: 'automation.risk = DANGEROUS',
    isActive: true,
  },
  {
    id: 'alert-006',
    title: 'GitHub token no remote credentials',
    description: 'GITHUB_TOKEN (ghp_*) está salvo no ~/.git-credentials do servidor. Risco de exfiltração.',
    severity: 'critical',
    category: 'security',
    source: 'guardiao_chaves',
    serviceId: 'git-credentials',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['telegram'],
    triggerCondition: 'ghp_ encontrado em ~/.git-credentials',
    isActive: true,
  },
  {
    id: 'alert-007',
    title: 'Vercel deploy falhou (arrudaimobi-ekxeewvsi)',
    description: 'Deploy com env vars metaads falhou com BUILD ERROR. Deploy anterior restaurado.',
    severity: 'warning',
    category: 'deploy',
    source: 'vercel',
    serviceId: 'vercel-deploy',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    acknowledged: true,
    resolvedAt: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    acknowledgedBy: 'Jack',
    notifiedVia: ['none'],
    triggerCondition: 'vercel deployment.readyState = ERROR',
    isActive: false,
  },
  {
    id: 'alert-008',
    title: 'Meta Ads — 2 leads sem conversão de compra',
    description: 'Campanhas de conversão têm 14 leads e 0 purchases. CPL está baixo (R$1.81) mas sem ROI mensurável.',
    severity: 'info',
    category: 'performance',
    source: 'meta_ads',
    serviceId: 'meta_ads',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
    resolvedAt: null,
    acknowledgedBy: null,
    notifiedVia: ['none'],
    triggerCondition: 'meta campaigns com leads > 0 + purchases = 0',
    isActive: true,
  },
];

// ─── Governance Items ──────────────────────────────────────────────────────────

export const governanceItems: GovernanceItem[] = [
  {
    id: 'gov-001',
    type: 'dangerous',
    severity: 'critical',
    title: 'LC-01 — Claw3D builder sem feature ativa',
    description: 'Cron executa builder a cada 1min mas feature_flag = false. Desperdício de recursos.',
    automationId: 'lc-01',
    serviceId: 'cron',
    owner: 'carlos',
    recommendedAction: 'Pausar cron LC-01 ou ativar feature flag',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isActionable: true,
  },
  {
    id: 'gov-002',
    type: 'dangerous',
    severity: 'critical',
    title: 'LC-07 — Builderfy syntax error silencioso',
    description: 'Comando com erro de sintaxe ignorado sem log. Cron executa sem efeito há semanas.',
    automationId: 'lc-07',
    serviceId: 'cron',
    owner: 'carlos',
    recommendedAction: 'Corrigir sintaxe ou remover cron LC-07',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    isActionable: true,
  },
  {
    id: 'gov-003',
    type: 'dangerous',
    severity: 'error',
    title: 'OC-01 — remote-access-research timeout loop',
    description: 'Automation dá timeout persistente. Gera erros no log a cada execução.',
    automationId: 'oc-01',
    serviceId: 'cron',
    owner: 'hunter',
    recommendedAction: 'Revisar endpoint ou desabilitar OC-01',
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    isActionable: true,
  },
  {
    id: 'gov-004',
    type: 'orphan',
    severity: 'warning',
    title: '5 automações sem owner',
    description: 'OC-02, OC-03, OC-04, OC-05, OC-06 não têm owner definido.',
    automationId: 'registry',
    serviceId: 'registry',
    owner: 'arruda_operator',
    recommendedAction: 'Atribuir owner a cada automação órfã',
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    isActionable: true,
  },
  {
    id: 'gov-005',
    type: 'critical',
    severity: 'critical',
    title: 'GitHub token em ~/.git-credentials',
    description: 'Token com permissões de push salvo em arquivo plain text no servidor.',
    serviceId: 'git-credentials',
    owner: 'main',
    recommendedAction: 'Remover token do credential store e usar token read-only para fetch',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    isActionable: true,
  },
  {
    id: 'gov-006',
    type: 'pending_approval',
    severity: 'info',
    title: 'Deploy produção aguardando aprovação',
    description: 'Branch arruda/ai-first-central-ia-draft pronta para produção. Aguardando Dogo aprovar.',
    serviceId: 'vercel',
    owner: 'diogo',
    recommendedAction: 'Revisar diff e aprovar ou rejeitar deploy',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isActionable: false,
  },
];

export function getActiveAlerts(): Alert[] {
  return alerts.filter(a => a.isActive && !a.acknowledged);
}

export function getActiveGovernanceItems(): GovernanceItem[] {
  return governanceItems.filter(g => g.isActionable);
}

export function getCriticalAlerts(): Alert[] {
  return alerts.filter(a => a.isActive && (a.severity === 'critical' || a.severity === 'error'));
}
